# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assignment_Title', models.CharField(max_length=30)),
                ('Assignment_Description', models.TextField()),
                ('Date_Of_Submission', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch_name', models.CharField(max_length=20)),
                ('Start_date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Max_no_of_student', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certificate_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=15)),
                ('Description', models.TextField()),
                ('Code', models.CharField(max_length=10)),
                ('Minimum_attendance_in_percent', models.DecimalField(decimal_places=0, max_digits=2)),
                ('Total_Working_Days', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Term', models.CharField(choices=[('First_Term', 'First_Term'), ('Second_term', 'Second_term'), ('Third_Term', 'Third_Term'), ('Final_Term', 'Final_Term')], max_length=10)),
                ('Exam_Name', models.CharField(max_length=15)),
                ('Full_marks', models.DecimalField(decimal_places=0, max_digits=3)),
                ('Pass_marks', models.DecimalField(decimal_places=0, max_digits=3)),
                ('Marks_obtained', models.DecimalField(decimal_places=0, max_digits=3)),
                ('Student_Unique_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Student_Admission')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notes_Title', models.CharField(max_length=30)),
                ('Notes_Description', models.TextField()),
                ('Batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.Batch')),
                ('Course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_name', models.CharField(max_length=20)),
                ('Subject_code', models.CharField(max_length=10)),
                ('Subject_description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='Subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.Subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='Subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.Subject'),
        ),
        migrations.AddField(
            model_name='batch',
            name='Course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.Course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='Batch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.Batch'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='Course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.Course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='Subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.Subject'),
        ),
    ]
