# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Admission',
            fields=[
                ('First_Name', models.CharField(max_length=10)),
                ('Middle_Name', models.CharField(max_length=10)),
                ('Family_Name', models.CharField(max_length=10)),
                ('Student_Unique_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_of_birth', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to specify', 'Prefer not to specify')], max_length=25)),
                ('Blood_Group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O', 'O-')], max_length=5)),
                ('Birth_place', models.CharField(max_length=20)),
                ('Nationality', models.CharField(max_length=10)),
                ('Mother_Tangue', models.CharField(max_length=10)),
                ('Religion', models.CharField(choices=[('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Islam', 'Islam'), ('Cristianity', 'Cristianity'), ('Other', 'Other')], max_length=10)),
                ('National_Identity_card_type', models.CharField(max_length=15)),
                ('National_ID_Card_Number', models.CharField(max_length=10)),
                ('Permanent_Address', models.CharField(max_length=25)),
                ('Present_Address', models.CharField(max_length=25)),
                ('City', models.CharField(max_length=25)),
                ('Zip', models.CharField(max_length=5)),
                ('State', models.CharField(choices=[('State-1', 'State-1'), ('State-2', 'State-2'), ('Stat-3', 'State-3'), ('State-4', 'State-4'), ('State-5', 'State-5'), ('State-6', 'State-6'), ('State-7', 'State-7')], max_length=10)),
                ('Country', models.CharField(max_length=25)),
                ('Phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Mobile', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Fathers_Name', models.CharField(max_length=25)),
                ('Fathers_Contact_Number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fathers_Profession', models.CharField(max_length=15)),
                ('Fathers_National_ID_Card_Number', models.CharField(max_length=10)),
                ('Mothers_Name', models.CharField(max_length=25)),
                ('Mothers_Contact_Number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Mothers_Profession', models.CharField(max_length=15)),
                ('Mothers_National_ID_Card_Number', models.CharField(max_length=10)),
                ('Local_Parents_Name', models.CharField(max_length=25)),
                ('Relationship', models.CharField(max_length=15)),
                ('Local_Parents_Profession', models.CharField(max_length=15)),
                ('Income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Previous_School_Name', models.CharField(max_length=25)),
                ('Previous_School_Address', models.CharField(max_length=25)),
                ('Latest_Qualification', models.CharField(max_length=10)),
                ('Hostel', models.CharField(choices=[('Day', 'Day'), ('Full', 'Full'), ('No', 'No')], max_length=10)),
                ('Transportation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='student_admission',
            name='Faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Student_Faculty'),
        ),
        migrations.AddField(
            model_name='student_admission',
            name='Grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Student_Grade'),
        ),
    ]
