# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-04 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel_Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hostel_Regd_Date', models.DateField()),
                ('Vacating_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Hostel_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hostel_type', models.CharField(choices=[('Boys-Hostel', 'Boys-Hostel'), ('Girls-Hostel', 'Girls-Hostel')], max_length=15)),
                ('Hostel_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_type', models.CharField(choices=[('Employee', 'Employee'), ('Student', 'Student'), ('Visitor', 'visitor'), ('Other', 'Other')], max_length=10)),
                ('Name', models.CharField(max_length=20)),
                ('In_out', models.CharField(choices=[('In', 'In'), ('Out', 'Out')], max_length=3)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Hostel_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Floor_Name_or_No', models.CharField(max_length=10)),
                ('Room_No', models.DecimalField(decimal_places=0, max_digits=5)),
                ('No_Of_Beds', models.DecimalField(decimal_places=0, max_digits=2)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Hostel_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hostel.Hostel_Details')),
            ],
        ),
        migrations.CreateModel(
            name='Hostel_Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visitors_Name', models.CharField(max_length=20)),
                ('Relation', models.CharField(max_length=15)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('User_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hostel.Hostel_Register')),
            ],
        ),
        migrations.AddField(
            model_name='hostel_allocation',
            name='Hostel_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hostel.Hostel_Details'),
        ),
        migrations.AddField(
            model_name='hostel_allocation',
            name='Room_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hostel.Hostel_Room'),
        ),
        migrations.AddField(
            model_name='hostel_allocation',
            name='User_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hostel.Hostel_Register'),
        ),
    ]
