# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-03 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Permanent_Address', models.CharField(max_length=25)),
                ('Present_Address', models.CharField(max_length=25)),
                ('Date_of_birth', models.DateField()),
                ('Phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('License_Number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Route_code', models.CharField(max_length=20)),
                ('Start_place', models.CharField(max_length=25)),
                ('Stop_place', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Transport_Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination', models.CharField(max_length=20)),
                ('Type_of_Pessenge', models.CharField(choices=[('Student', 'Student'), ('Employee', 'Employee')], max_length=10)),
                ('Frequency', models.DecimalField(decimal_places=0, max_digits=2)),
                ('Route_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transport.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_Number', models.CharField(max_length=15)),
                ('No_Of_Seats', models.DecimalField(decimal_places=0, max_digits=3)),
                ('Maximum_allowed', models.DecimalField(decimal_places=0, max_digits=3)),
                ('Vehicle_type', models.CharField(choices=[('Contract', 'Contract'), ('Ownership', 'Ownership')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='Vehicle_Number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transport.Vehicle'),
        ),
        migrations.AddField(
            model_name='driver',
            name='Vehicle_Number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transport.Vehicle'),
        ),
    ]
